#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
final_table.py  --  Letter v3.  Corrected 2026-07-21.

Emits the LaTeX table bodies of Section 5 and Appendix A *from the computation*,
so the manuscript can be diffed against them instead of transcribed by hand.
Hand transcription is what produced the v2 errors (eq. 10, and the exponent in
"(lambda-lambda_0)^-2").

Usage:  python final_table.py            # prints LaTeX to stdout
"""
import sympy as sp
import numpy as np
from flow_coeffs import coeffs, collapse, z_of_lambda, MUS, PHI0, OMEGA_M

tex = lambda e: sp.latex(e) if e is not None else "---"

print("% " + "=" * 74)
print("% AUTO-GENERATED by final_table.py -- do not edit by hand")
print(f"% Phi0 = {PHI0}, Omega_m = {OMEGA_M}")
print("% " + "=" * 74)

print("\n%%% Table 1 (Section 5): exclusion table")
print(r"\begin{tabular}{lccccc}")
print(r"\toprule")
print(r"$\mu(x)$ & $c_{2}$ & $c_{3}$ & $\beta'(0)$ & $\kappa$ & $z_{*}$ \\")
print(r"\midrule")
names = {"Standard  x/sqrt(1+x^2)": r"Standard  $x/\sqrt{1+x^{2}}$",
         "mu-hat entropic": r"$\hat\mu$ entropic $\sqrt{1+(2x)^{-2}}-(2x)^{-1}$",
         "tanh(x)": r"$\tanh(x)$",
         "Simple    x/(1+x)": r"Simple  $x/(1+x)$",
         "TeVeS toy": r"TeVeS toy  $2x/(1+2x+\sqrt{1+4x})$",
         "Exponential 1-e^-x": r"Exponential  $1-e^{-x}$"}
for i, (name, mu) in enumerate(MUS):
    if i == 3:
        print(r"\midrule")
    c2, c3, bp, kap = coeffs(mu)
    lam, _ = collapse(mu)
    zs = f"${z_of_lambda(lam):.2f}$" if lam is not None else "---"
    print(f"{names[name]} & ${tex(c2)}$ & ${tex(c3)}$ & "
          f"{('$'+tex(bp)+'$') if bp is not None else '---'} & "
          f"{('$'+tex(kap)+'$') if kap is not None else '---'} & {zs} \\\\")
print(r"\bottomrule")
print(r"\end{tabular}")

print("\n%%% Table (Appendix A.7): numerical integration of the exact flow")
print(r"\begin{tabular}{lccc}")
print(r"\toprule")
print(r"$\mu(x)$ & $c_{2}$ & $\Phi(\lambda=1)$ & $\lambda_{*}$ \\")
print(r"\midrule")
for name, mu in MUS:
    c2, _, _, _ = coeffs(mu)
    lam, sol = collapse(mu)
    if lam is not None and lam < 1:
        p1 = "$0$"
    else:
        from scipy.integrate import solve_ivp
        mp = sp.diff(mu, x := sp.Symbol('x', positive=True))
        p1v = np.interp(1.0, sol.t, sol.y[0])
        p1 = f"${p1v:.2e}$".replace("e-0", r"\times10^{-") + "}$" if False else \
             "$%.2f\\times10^{-2}$" % (p1v*100)
    print(f"{names[name]} & ${tex(c2)}$ & {p1} & "
          f"{(f'${lam:.3f}$' if lam is not None else '---')} \\\\")
print(r"\bottomrule")
print(r"\end{tabular}")

print("\n% " + "=" * 74)
print("% Sanity: the standard function must give beta'(0)=-1, kappa=+1/2")
c2, c3, bp, kap = coeffs(MUS[0][1])
assert (c2, c3, bp, kap) == (0, sp.Rational(-1, 2), -1, sp.Rational(1, 2)), "TABLE MISMATCH"
print("% PASS")
